#!/usr/bin/env bash
# FizzBuzz - display ffrom one to 100, "Fizz" for multiplication of 3,
# "Buzz" for multiplicatio of 5, and "FizzBuzz" for multiplications of 3 and 5

for (( n=1; n < 101; n++ ))
do
    if (( n % 15 == 0 )); then
	echo "FizzBuzz"
    elif (( n % 3 == 0 )); then
	echo "Fizz"
    elif (( n % 5 == 0 )); then
	echo "Buzz"
    else
	echo "$n"
    fi
done

