#!/usr/bin/env bash
# this go through the file and manipulates field to get the stor

FILE="/etc/passwd"

while IFS=":" read -r user pw uid gid uinfo homedir shell
do
    echo "The user $user is part of the $gid gang, lives in $homedir and \
rides $shell. $uid's place is protected by the passcode $pw, \
more info about the user here: $uinfo"
done < "$FILE"

