#!/usr/bin/env bash
# Ishmael Dukuly
# Output the hrs: from 1 to 20, mins 1 to 59

hr=0
while [ "$hr" -le 12 ]
do
    echo "Hour: $hr"
    (( hr++ ))

    min=1
    while [ "$min" -le 59 ]
    do
	echo "$min"
	(( min++ ))
    done
done

